version: '3.6'

services:
  db:
    restart: always
    image: 'postgres:13.1-alpine'
    container_name: hhub-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}